name: Build Executable file

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install --verbose

      - name: Install Linux dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0 libnss3 libxss1 libasound2

      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          git config --global core.symlinks true
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          npm run build:win --verbose

      - name: Build app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run build:mac --verbose

      - name: Build app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux --verbose

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-builds-${{ matrix.os }}
          path: dist/**
