name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'   # Run only when a version tag (e.g., v1.0.0) is pushed
    branches:
      - 'main'  # Also run on main branch for testing

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Build for each platform with special handling for Windows symlinks
      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          # Enable symlinks in git
          git config --global core.symlinks true
          # Run the build with proper symlink handling
          npm run build:win

      - name: Build app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: build-${{ matrix.os }}
          path: dist/**
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    # Only run on tag pushes
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4  # Updated to v4
        with:
          path: ./artifacts

      # Prepare artifacts for release
      - name: Prepare release files
        run: |
          mkdir -p release-files
          # Move each OS artifact to the release directory with proper naming
          find ./artifacts -type f -name "*.exe" -exec cp {} release-files/ \;
          find ./artifacts -type f -name "*.dmg" -exec cp {} release-files/ \;
          find ./artifacts -type f -name "*.AppImage" -exec cp {} release-files/ \;
          ls -la release-files/

      # Create GitHub Release with the artifacts
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
