name: Build and Release Executables

on:
  push:
    tags:
      - 'v*'
    branches:
      - 'main'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build app (Windows)
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: npm run build:win

      - name: Build app (macOS)
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: Build app (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/**
          retention-days: 5

  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Prepare release files
        run: |
          mkdir -p release-files
          find ./artifacts -type f -name "*.exe" -exec cp {} release-files/ \;
          find ./artifacts -type f -name "*.dmg" -exec cp {} release-files/ \;
          find ./artifacts -type f -name "*.AppImage" -exec cp {} release-files/ \;

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: release-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
